services:
    psql:
        image: postgres:16.3
        restart: no
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    api:
        build:
            context: .
            target: base
        env_file:
            - .env
        ports:
            - "3001:3001"
        command: ./main
        depends_on:
            - psql
        networks:
            - primary

networks:
    primary:
        external: true

