services:
    psql:
        image: postgres:16.3
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        environment:
            - DB_URL=postgres://postgres:12345@psql:5432/postgres?sslmode=disable
            - PORT=3001
        ports:
            - "3001:3001"
        command: sh -c "sleep 5 && goose -dir sql/migrations postgres $DB_URL up && ./main"
        networks:
            - primary

networks:
    primary:

