services:
    psql:
        image: postgres:16.3
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        env_file:
            - .env
        ports:
            - "3001:3001"
        command: ./main
        networks:
            - primary

networks:
    primary:

